// wallNetwork.js
//
// THIS FILE IS THE ACTUAL FIX for the complaint that killed the first
// preview (see .preview/sample_floor_plan.svg, generated by an earlier,
// now-abandoned scratch script - gitignored, never committed - which drew
// one flat-coloured rectangle per room with visible gaps between them,
// nothing touching, nothing that reads as "a building"). That preview drew
// walls the wrong way round: PER ROOM, each room outlining its own box in
// isolation, with no idea any other room existed.
//
// A real building doesn't work like that - two rooms that sit side by side
// share the ACTUAL PHYSICAL WALL between them. This file builds the wall
// network the way an architect actually would: collect every room's edges
// into one shared pool, find which edges from DIFFERENT rooms describe the
// same physical wall line, and merge them into single continuous
// segments. A wall between bedroom_0 and bedroom_1 is drawn exactly once,
// not as two competing rectangles with a hairline gap between them.
//
// Ported (concept only - the source is Python/matplotlib, working from a
// completely different room representation) from
// D:\ai-floor-planner\python\app\floor_generator\cad_render.py's
// build_interior_walls / build_exterior_walls (WallSegment class,
// merge_intervals, cluster_coords). That project's rooms came out of a
// trained model + corrector that pulls boxes to near-exact contact, so its
// clustering tolerance (WALL_SNAP = 0.08m) could stay tiny. Ours doesn't
// have a model - see the WALL_SNAP/MERGE_TOL comment below for why this
// project needs a different, empirically-checked value instead of copying
// that number over.

import { estimatePlotDimensions } from "../ruleEngine/plotSizing.js";

// ---------------------------------------------------------------------
// Wall thickness constants (metres). These are standard residential
// construction dimensions, not something derived from this project's data
// - the same numbers the reference file used, since "how thick is an
// interior stud wall" is architecture knowledge, not something tied to our
// unit-space quirks:
//   - an interior partition wall (timber/steel stud + board on both sides)
//     is typically ~90-100mm;
//   - an exterior wall (structural + insulation + external finish) is
//     typically ~180-230mm, roughly double an interior wall.
// ---------------------------------------------------------------------
export const INT_WALL_T = 0.10; // interior wall thickness (m)
export const EXT_WALL_T = 0.20; // exterior wall thickness (m) - ~2x interior, matches real construction

// ---------------------------------------------------------------------
// WALL_SNAP / MERGE_TOL - the tolerances that make disconnected boxes into
// a connected wall network. This is the number that actually needed
// re-deriving for OUR pipeline rather than copying from the reference file,
// and here's why:
//
// seeding.js places two rooms that are meant to sit side by side with a
// small SEED_GAP (0.02 in the rule engine's normalised unit space) between
// their facing edges, not touching at 0. solver.js only closes that gap
// further if the room has an actual "problem" (a collision, or an
// attach-map relationship whose gap exceeds ADJACENCY_TOLERANCE = 0.03
// units) - a plain sibling-to-sibling gap (e.g. bedroom_0 next to
// bedroom_1, both just part of the same row, with no attach-map entry
// between them) is already "close enough" the moment it's seeded and is
// NEVER touched again. So real solved layouts keep a small but genuine gap
// between visually-adjacent rooms, not an exact 0.
//
// Measured directly (not guessed) by running the actual pipeline
// (buildRoomProgram -> buildAttachMap -> seedLayout -> solveLayout) across
// several room programs and converting every room pair's edge-to-edge gap
// into real metres via metersPerUnit: every genuinely-adjacent pair (rooms
// that should read as sharing a wall) landed at 0.000m-0.412m. The very
// next closest "these two rooms are NOT actually neighbours, their
// bounding spans just happen to overlap a little" pair was 1.589m away -
// a roughly 4x jump, a clean gap in the distribution to draw a threshold
// in. WALL_SNAP is set comfortably above the real-adjacency ceiling
// (0.412m) and comfortably below the first false-positive (1.589m), so it
// reliably welds true shared walls into one line without accidentally
// fusing two walls that were never meant to be the same one.
//
// (The reference project's own WALL_SNAP = 0.08m would be far too tight
// here - it would treat almost every genuinely-adjacent pair in our output
// as two separate, unconnected wall lines with a visible dead-space sliver
// between them, reproducing exactly the "boxes don't connect" complaint
// this file exists to fix.)
export const WALL_SNAP = 0.50; // m - tolerance for treating two edges as "the same wall line"
// MERGE_TOL governs a different question: once two edges ARE agreed to sit
// on the same wall LINE (same clustered coordinate), do their spans along
// that line touch closely enough to merge into one continuous drawn
// segment (rather than being drawn as two separate pieces on the same
// line, with a real hole between them)? Kept a little smaller than
// WALL_SNAP, matching the reference file's own WALL_SNAP > MERGE_TOL
// relationship, since this only ever has to bridge the same small
// seed/solver gaps described above, never a genuinely different wall.
export const MERGE_TOL = 0.40; // m

// ---------------------------------------------------------------------
// roomsToMeters - converts solveLayout()'s unit-space room boxes into
// real-world metres, anchored so the tightest bounding box of the rooms
// starts at (0, 0).
//
// solveLayout()'s output ({ rooms, plot }) deliberately keeps `plot.widthM`
// / `plot.depthM` as the only real-metre numbers it returns - room
// cx/cy/w/h stay in the rule engine's normalised unit space (see the
// heads-up left in STATUS.md's Day 7-8 section). To draw anything, this
// renderer needs every room's box in the SAME real-world metres `plot`
// already uses. metersPerUnit is recomputed here via
// estimatePlotDimensions(rooms) rather than solveLayout() being changed to
// return it - STATUS.md flagged this as the safe option: that function
// only reads each room's `.type`, never its position, so calling it again
// on the same room list reproduces the exact same factor solveLayout()
// used internally, with zero risk of drifting from it.
//
// The shift-by-bounding-box-minimum step matters because unit-space
// coordinates are NOT anchored at (0, 0) - kitchen/storage rooms, for
// instance, are seeded to the LEFT of living (negative cx). Subtracting the
// layout's own minimum x/y (the same values solveLayout() used to measure
// plot.widthM/depthM as maxX-minX) is what makes the converted room boxes
// line up exactly inside the [0, plot.widthM] x [0, plot.depthM] rectangle
// the exterior wall gets drawn at - same anchoring convention
// solveLayout() already established, just applied per-room instead of only
// to the overall bounding box.
export function roomsToMeters(rooms, plot) {
  const { metersPerUnit } = estimatePlotDimensions(rooms);

  let minX = Infinity;
  let minY = Infinity;
  for (const room of rooms) {
    minX = Math.min(minX, room.cx - room.w / 2);
    minY = Math.min(minY, room.cy - room.h / 2);
  }

  return rooms.map((room) => {
    const x1 = (room.cx - room.w / 2 - minX) * metersPerUnit;
    const x2 = (room.cx + room.w / 2 - minX) * metersPerUnit;
    const y1 = (room.cy - room.h / 2 - minY) * metersPerUnit;
    const y2 = (room.cy + room.h / 2 - minY) * metersPerUnit;

    // roomProgram.js always builds ids as `${type}_${typeIndex}` (see its
    // Step 3) - parsing that back out here is how the renderer knows
    // "this is the first/master bedroom" or "this is bathroom number 2 of
    // 3" for labelling, without solveLayout() needing to carry a separate
    // typeIndex field through seeding/solving just for this.
    const typeIndex = Number(room.id.slice(room.type.length + 1));

    return {
      id: room.id,
      type: room.type,
      typeIndex,
      x1,
      y1,
      x2,
      y2,
      cx: (x1 + x2) / 2,
      cy: (y1 + y2) / 2,
      w: x2 - x1,
      h: y2 - y1,
    };
  });
}

// ---------------------------------------------------------------------
// Small geometry helpers used only by the wall-building logic below.
// ---------------------------------------------------------------------

// Groups sorted-by-value numbers into clusters where each value is within
// `tol` of the PREVIOUS value already in its cluster (a classic "chain"
// clustering - if A and B are close, and B and C are close, A and C end up
// in the same cluster even if A and C themselves are further apart than
// `tol`). This is the same approach the reference file uses; it is a known,
// accepted simplification here rather than something stricter (e.g.
// clustering against a cluster's average) because the WALL_SNAP comment
// above already confirmed there is a large, clean gap (0.412m to 1.589m)
// between real adjacent-wall gaps and the next accidental near-miss in
// every configuration checked - not enough genuinely-close-but-unrelated
// coordinates for chaining to actually misfire in practice.
function clusterCoords(values, tol) {
  if (values.length === 0) return [];
  const sorted = [...values].sort((a, b) => a - b);
  const clusters = [[sorted[0]]];
  for (let i = 1; i < sorted.length; i++) {
    const value = sorted[i];
    const currentCluster = clusters[clusters.length - 1];
    if (value - currentCluster[currentCluster.length - 1] <= tol) {
      currentCluster.push(value);
    } else {
      clusters.push([value]);
    }
  }
  // Represent each cluster by the average of its members - splits the
  // difference of whatever small real gap put them in the same cluster in
  // the first place, rather than arbitrarily picking the first or last.
  return clusters.map((cluster) => cluster.reduce((sum, v) => sum + v, 0) / cluster.length);
}

// Merges a list of [start, end] intervals that overlap OR sit within `tol`
// of each other into the smallest set of non-overlapping intervals that
// still covers everything. This is the step that turns "bedroom_0's edge
// from y=6.3 to y=10.0" and "bedroom_1's edge from y=6.3 to y=10.0" (already
// agreed, by clusterCoords above, to be on the same wall LINE) into one
// continuous wall SEGMENT instead of two separately-drawn, coincidentally
// overlapping rectangles.
function mergeIntervals(intervals, tol) {
  if (intervals.length === 0) return [];
  const sorted = [...intervals].sort((a, b) => a[0] - b[0]);
  const merged = [[...sorted[0]]];
  for (let i = 1; i < sorted.length; i++) {
    const [start, end] = sorted[i];
    const last = merged[merged.length - 1];
    if (start <= last[1] + tol) {
      last[1] = Math.max(last[1], end);
    } else {
      merged.push([start, end]);
    }
  }
  return merged;
}

// ---------------------------------------------------------------------
// Interior wall network
// ---------------------------------------------------------------------

// Builds the interior wall segments by pooling every room's edges together
// and clustering/merging them, per the big comment at the top of this file.
//
// front_door is deliberately excluded from contributing edges here - it's
// not a walled room, it's a marker for "cut a door into the exterior wall
// near here" (handled by doors.js's placeFrontDoor). Including it would
// draw a small, pointless interior wall sliver right where the entrance
// itself should be an opening.
//
// Edges that sit essentially ON the plot boundary (within WALL_SNAP of x=0,
// x=W, y=0 or y=D) are also excluded - a room whose own edge happens to
// BE the building's outer edge doesn't need its own interior wall segment
// competing with the exterior wall already drawn at that same location by
// buildExteriorWalls() below.
function buildInteriorWalls(meterRooms, W, D) {
  const vEdges = []; // vertical edges: { x, y1, y2 }
  const hEdges = []; // horizontal edges: { y, x1, x2 }

  for (const room of meterRooms) {
    if (room.type === "front_door") continue;

    for (const x of [room.x1, room.x2]) {
      if (x > WALL_SNAP && x < W - WALL_SNAP) {
        vEdges.push({ x, y1: room.y1, y2: room.y2 });
      }
    }
    for (const y of [room.y1, room.y2]) {
      if (y > WALL_SNAP && y < D - WALL_SNAP) {
        hEdges.push({ y, x1: room.x1, x2: room.x2 });
      }
    }
  }

  const segments = [];

  for (const coord of clusterCoords(vEdges.map((e) => e.x), WALL_SNAP)) {
    const intervals = vEdges
      .filter((e) => Math.abs(e.x - coord) <= WALL_SNAP)
      .map((e) => [e.y1, e.y2]);
    for (const [start, end] of mergeIntervals(intervals, MERGE_TOL)) {
      if (end - start > 1e-6) {
        segments.push({ orientation: "v", coord, start, end, thickness: INT_WALL_T, cuts: [] });
      }
    }
  }

  for (const coord of clusterCoords(hEdges.map((e) => e.y), WALL_SNAP)) {
    const intervals = hEdges
      .filter((e) => Math.abs(e.y - coord) <= WALL_SNAP)
      .map((e) => [e.x1, e.x2]);
    for (const [start, end] of mergeIntervals(intervals, MERGE_TOL)) {
      if (end - start > 1e-6) {
        segments.push({ orientation: "h", coord, start, end, thickness: INT_WALL_T, cuts: [] });
      }
    }
  }

  return segments;
}

// The exterior wall is simply the plot's own rectangle boundary - four
// segments, one per side, always full-length and always present regardless
// of what the interior layout looks like. Thicker than interior walls (see
// EXT_WALL_T above) so the drawing visually reads "this is the outside of
// the building" at a glance, the same convention real architectural
// drawings use.
function buildExteriorWalls(W, D) {
  return [
    { orientation: "v", coord: 0, start: 0, end: D, thickness: EXT_WALL_T, cuts: [] },
    { orientation: "v", coord: W, start: 0, end: D, thickness: EXT_WALL_T, cuts: [] },
    { orientation: "h", coord: 0, start: 0, end: W, thickness: EXT_WALL_T, cuts: [] },
    { orientation: "h", coord: D, start: 0, end: W, thickness: EXT_WALL_T, cuts: [] },
  ];
}

/**
 * Build the full wall network (interior + exterior) for a solved layout.
 *
 * @param {Array<{id: string, type: string, cx: number, cy: number, w: number, h: number}>} rooms
 *   solveLayout()'s `rooms` output (unit-space).
 * @param {{ widthM: number, depthM: number, areaM2: number }} plot
 *   solveLayout()'s `plot` output.
 * @returns {{
 *   meterRooms: Array<object>,   // every room, converted to real metres (see roomsToMeters)
 *   W: number, D: number,        // plot width/depth in metres (== plot.widthM/depthM)
 *   interiorWalls: Array<object>,
 *   exteriorWalls: Array<object>,
 * }}
 *   Each wall segment is `{ orientation: 'v'|'h', coord, start, end, thickness, cuts: [] }`.
 *   `cuts` starts empty here - doors.js's placeDoors() fills it in with
 *   `{ gapStart, gapEnd, inwardDx, inwardDy }` entries for wherever a door
 *   opening should be cut out of that segment when it's drawn.
 */
export function buildWallNetwork(rooms, plot) {
  const meterRooms = roomsToMeters(rooms, plot);
  const W = plot.widthM;
  const D = plot.depthM;

  return {
    meterRooms,
    W,
    D,
    interiorWalls: buildInteriorWalls(meterRooms, W, D),
    exteriorWalls: buildExteriorWalls(W, D),
  };
}
